import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import LineChart from '@/components/LineChart'
import AreaChart from '@/components/AreaChart'
import RadarChart from '@/components/RadarChart'
import Image from 'next/image'



export default function Home() {
  return (
    <>
      <Head>
        <title>Japan Chart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div 
      className={styles.japan_pic}>

      <Image
            src="/japanmap.png" 
            alt=""
            width={650}
            height={400}
      />

      </div>

    <main 
    className={styles.main}>
     
     <LineChart
     className={styles.linechart}
     />

     <AreaChart
     className={styles.areachart}
     />

     <RadarChart
     className={styles.radarchart}
     />
      
    </main>
    </>
  )
}
